[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "cmake", "gcc", "libffi", "openssl", "zlib"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python -m gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 'app:create_app()'"
