[phases.setup]
nixPkgs = ["cmake", "gcc", "libffi", "openssl", "zlib"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 'app:create_app()'"
